<?php

/*
* implementing hook_services_resources
*/

function saed_webservice_services_resources(){
        $resources = [
            'custom_node' => [
                'operations' => [
                    'index' => [
                      'help' => 'Retrieve a node list based on his type',
                      'file' => [
                          'type' => 'inc',
                          'module' => 'saed_webservice',
                          'name' => 'saed_webservice',
                      ],
                      'callback' => '_saed_webservice_index',
                      'access callback' => 'user_is_logged_in',
                      'args' => [
                          [
                            'name' => 'type_name',
                            'optional' => FALSE,
                            'source' => [
                                'path' => 0
                            ],
                            'type' => 'string',
                            'description' => 'Machine-readable name of node type',
                          ],
                      ],  
                    ],
                ],
            ],
        ];
        return $resources;
}
